### ISSUE TITLE
Name already used in NPM

### ISSUE THREAD

**Issue by guumaster** [thegameofcode/resonator#1]
Hermes is a good name, but there is already a NPM package with that name: [Hermes](https://www.npmjs.com/package/hermes)

**Comment by luismesas** [comment]
we need a name!!!, just say one and lets see

**Comment by unlogic** [comment]
I have some great names:

Ansible <https://en.wikipedia.org/?title=Ansible>

FTL (faster-than-light)
<https://en.wikipedia.org/wiki/Superluminal_communication>

Quantum <https://en.wikipedia.org/?title=Quantum>

Resonator <https://en.wikipedia.org/wiki/Resonator>

**Comment by nick13jaremek** [comment]
Here is a list of names I wrote down some time ago:

Paperplane
Paperdove
Bitcarrier
Bitgeon
Bitdove
Technotifier
Bitemitter
Droidgeon
Bitbird or Bytebird
Sparrowbit or Sparrowbyte
Piobit
Birdhub
Dovehub
Sparrowhub
Crowhub
Crowcluster

None of these are registered as modules on the NPM site. 

My preference goes to the Crowcluster name, maybe even Birdhub or Crowhub.

What would be you choice?

**Comment by lekum** [comment]
What about *NODEtify*?

**Comment by guumaster** [comment]
It seems resonator is already associated with this repo. I say we rename this repo to `resonator`  and lets code! :+1:

**Comment by luismesas** [comment]
Yes, I just changed the package name on the mobile and post to reserve the
name. Let me know if it sounds ok to everyone

2015-06-22 9:48 GMT-07:00 Gustavo <notifications@github.com>:

> It seems resonator is already associated with this repo. I say we rename
> this repo to resonator and lets code! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thegameofcode/hermes/issues/1#issuecomment-114176398>.
>



-- 

*Luis Mesas*
*t:*  +1 415 886 5471
*e:*  luis.mesas@intelygenz.com
*w:*  www.intelygenz.com <http://www.intelygenz.com/en/>
350 Townsend St #407, San Francisco, CA 94107 U.S.A.
*Intelygenz. If you have a dream, we can write the code*

**Comment by unlogic** [comment]
Code, Code, Code!

Jonás da Cruz
