### ISSUE TITLE
Add environment variables

### ISSUE THREAD

**Issue by igzdavidsuarez** [thegameofcode/resonator#17]
In order to pass all tests should be necessary to set up the APN_PFX environment variable to 'aps-test.p12' which is the value of the APN certificate.

At this moment tests are passing without set this variable if we run it using 'npm run test' because it run all the tests at the same time but it should not work so here we have a bug.

If we just run the push notification tests then it fails because it is realizing that the APN_PFX is missing, so it works correctly.

We have to detect why if we execute all tests with 'npm run test' it is not checking that the APN_PFX variable is missing.

To run just the push notification test use the following command:

NODE_ENV=test APN_PFX=aps-test.p12  node_modules/cucumber/bin/cucumber.js cucumber/features/push_notification_features/ -r cucumber/features/support/ -r cucumber/features/step_definitions/

**Comment by nick13jaremek** [comment]
Even though the tests report green, one of them fails internally causing the build on CircleCI to fail. The error is of type TransmissionError and its cause is the lack of a valid certificate/key for the APN module.

We either need to create a valid certificate for development or mock the APN requests, avoiding actual requests to the Apple's servers.

@igzdavidsuarez @guumaster

**Comment by nick13jaremek** [comment]
Turns out the APN library throws multiple errors which do not stop its execution, but they mess up with the test commands output. Pull request #24 adds a Mocha test for the APN push platform skipping the logic related to the APN library, and also ignores for now the Cucumber tests related to the APN Push notifications.

**Comment by guumaster** [comment]
fixed by #26.
