### ISSUE TITLE
Return suitable error messages on each platform

### ISSUE THREAD

**Issue by nick13jaremek** [thegameofcode/resonator#25]
Right now all the platforms (except Channel) have their errors managed by their corresponding router. However, the very same platforms should raise error messages that would be delivered to the requester as a HTTP message with the `statusCode` and `message` fields.

**Comment by nick13jaremek** [comment]
As suggested by @guumaster, we could try using [this error handler in restify mode.](https://github.com/ericelliott/express-error-handler)

**Comment by guumaster** [comment]
I think this is done after #35 and #33
