### ISSUE TITLE
Dredd doesn't compile in Node v4+

### ISSUE THREAD

**Issue by guumaster** [thegameofcode/resonator#46]
Should we disable dredd tests until they fix the tool?

**Comment by nick13jaremek** [comment]
Perhaps we could keep the eslinted branch as an independent one, making it optional for whoever wishes to use it?

Alternatively, we could merge both branches into `master` and wait until the team behind the `dredd` module provides support for Node 4.x.x.

**Comment by guumaster** [comment]
Support for Node 4.x is [on the way](https://github.com/apiaryio/dredd/blob/master/README.md)
